config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'messages#index'
  resources :messages
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    Message.create(message_params)
    redirect_to root_path
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.user_id == current_user.id
       @message.update(message_params)
       redirect_to root_path
    end
  end

  def destroy
    @message = Message.find(params[:id])
    if @message.user_id == current_user.id
       @message.destroy
       redirect_to root_path
    end
  end

  private
  
  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @message = @user.messages.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type = "text/css" href = "./style.css"></style>

      <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

      <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class = "cyan lighten-4">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo center">Blog</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
      <li><%= link_to "New", new_message_path  %></li>
    </ul>
  </div>
</nav>
    <%= yield %>
    <script type = "text/javascript" src = "./app.js"></script>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="row">
  <div class="col s12 m6 offset-m3 ">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <form class="new_message" id="new_message" action="/messages" accept-charset="UTF-8" method="post">
        <label for="message_content"></label>
        <%= message.text %>
      </div>
        <% if user_signed_in? && current_user.id == message.user_id %>
        <div class="card-action">
        <%= link_to "Show", "/users/#{current_user.id}" %>
        <%= link_to "Edit","/messages/#{message.id}/edit", method: :get %>
        <%= link_to "Destroy","/messages/#{message.id}", method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/messages/edit.html.erb
<div class="row">
  <div class="col s12 m6 offset-m3 ">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <%= form_for [@message] do |f| %>
          <%= f.label :text, :blog %>
          <%= f.text_field :text %>
          <%= f.submit "送信する", class: "blue-grey darken-1"%>
         <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/messages/index.html.erb
<% @message.each do |message| %>
<%= render partial: "message", locals: {message:message} %>
  <% end %>

app/views/messages/new.html.erb
<div class="row">
  <div class="col s12 m6 offset-m3 ">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <%= form_for [@message] do |f| %>
          <%= f.label :text, :blog %>
          <%= f.text_field :text %>
          <%= f.submit "送信する", class: "blue-grey darken-1"%>
         <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% @message.each do |message| %>
<%= render partial: "messages/message", locals: {message:message} %>
  <% end %>